CREATE TABLE IF NOT EXISTS `user` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    authority VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS note (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT chk_title_length CHECK (CHAR_LENGTH(title) BETWEEN 2 AND 100),
    CONSTRAINT chk_content_length CHECK (CHAR_LENGTH(content) <= 1000),
    CONSTRAINT fk_note_user FOREIGN KEY (user_id) REFERENCES `user` (id)
);